/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_config_free: (a: number, b: number) => void;
export const __wbg_get_config_endpoints: (a: number) => number;
export const __wbg_set_config_endpoints: (a: number, b: number) => void;
export const config_local: () => number;
export const config_pimlico: () => number;
export const __wbg_endpoints_free: (a: number, b: number) => void;
export const __wbg_get_endpoints_rpc: (a: number) => number;
export const __wbg_set_endpoints_rpc: (a: number, b: number) => void;
export const __wbg_get_endpoints_bundler: (a: number) => number;
export const __wbg_set_endpoints_bundler: (a: number, b: number) => void;
export const __wbg_get_endpoints_paymaster: (a: number) => number;
export const __wbg_set_endpoints_paymaster: (a: number, b: number) => void;
export const endpoints_new: (a: number, b: number, c: number) => number;
export const endpoints_live: () => number;
export const endpoints_local: () => number;
export const endpoints_pimlico: () => number;
export const __wbg_endpoint_free: (a: number, b: number) => void;
export const __wbg_get_endpoint_base_url: (a: number) => [number, number];
export const __wbg_set_endpoint_base_url: (a: number, b: number, c: number) => void;
export const __wbg_get_endpoint_api_key: (a: number) => [number, number];
export const __wbg_set_endpoint_api_key: (a: number, b: number, c: number) => void;
export const endpoint_new: (a: number, b: number, c: number, d: number) => number;
export const endpoint_local_rpc: () => number;
export const endpoint_local_bundler: () => number;
export const endpoint_local_paymaster: () => number;
export const __wbg_client_free: (a: number, b: number) => void;
export const client_new: (a: number, b: number, c: any) => number;
export const client_prepare: (a: number, b: number, c: number, d: number, e: number, f: any) => any;
export const client_get_ui_fields: (a: number, b: any, c: number) => any;
export const client_prepare_detailed: (a: number, b: number, c: number, d: number, e: number, f: any, g: number) => any;
export const client_status: (a: number, b: number, c: number) => any;
export const client_wait_for_success: (a: number, b: number, c: number, d: bigint) => any;
export const client_wait_for_success_with_timeout: (a: number, b: number, c: number, d: bigint, e: bigint) => any;
export const client_execute: (a: number, b: any, c: number, d: number, e: number, f: number) => any;
export const client_erc20_token_balance: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_export_5: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__heb3f862823f1d1fd: (a: number, b: number) => void;
export const closure777_externref_shim: (a: number, b: number, c: any) => void;
export const closure1016_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
