name: "CTA Assistant"

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  cta_assistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CTA Assistant"
        uses: WalletConnect/actions/github/cta-assistant@9fd44c01c5f8c169349f8822efc93dd08821a628
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}